### ISSUE TITLE
 Error loading webview ... Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by StoyanStAtanasov** [Huachao/vscode-restclient#1075]
- REST Client Version: v0.25.1
- VSCode Version: 1.72.0
- OS Version: Microsoft Windows Verion 21H2 (Build 22000.987)

Steps to Reproduce:

1. Sent request to local server: 
@ccUrl = localhost
GET https://{{ccUrl}}/smart-data
  ?apiToken=xxxxx&productNumber=CP96SB32-25C
3. Get: notificationsAlerts.ts:42 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
![image](https://user-images.githubusercontent.com/49271294/194591700-8b27974f-ac37-499d-b8b7-f08a1c55692f.png)

Also in the Extensions log:
[2022-10-07 16:50:44.867] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'uri')
    at t.DocumentCache.getKey (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:1:173560)
    at t.DocumentCache.has (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:1:173451)
    at l.getRequestVariables (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:1:174681)
    at l.has (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:1:174117)
    at Function.processRawRequest (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:7:1630)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.HttpDocumentSymbolProvider.getRequestSymbolInfo (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:686:27582)
    at t.HttpDocumentSymbolProvider.provideDocumentSymbols (c:\Users\StoyanAtanasov\.vscode\extensions\humao.rest-client-0.25.1\dist\extension.js:686:27218)
    at n.provideDocumentSymbols (c:\Users\StoyanAtanasov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:37375)

**Comment by peterlil** [comment]
I experience the same issue.

**Comment by asfernandes** [comment]
Same problem after update VSCode to 1.73.1

**Comment by asfernandes** [comment]
In my case it worked after restart.

**Comment by JannieT** [comment]
@asfernandes what did you restart?

**Comment by asfernandes** [comment]
The computer.

**Comment by StoyanStAtanasov** [comment]
FYI My issues have resolved some time ago. I don't even remember; it must have been and update either from vscode or the extension. I forgot to post earlier, sorry. I will close the issue.

**Comment by StoyanStAtanasov** [comment]
FYI My issues have resolved some time ago. I don't even remember; it must have been and update either from vscode or the extension. I forgot to post earlier, sorry. I will close the issue.
