### ISSUE TITLE
Extension fails to install in Docker Alpine dev container

### ISSUE THREAD

**Issue by bjanders** [Huachao/vscode-restclient#1087]
- REST Client Version: v0.25.1
- VSCode Version: 1.73.1 
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Install golang:1.19.3-alpine3.16 in a Docker
2. Attach VS Code to the container
3. Install REST Client in Dev Container

Install fails, and the following log is shown.

```
2022-11-11 11:31:11.684 [info] Getting Manifest... humao.rest-client
2022-11-11 11:31:11.961 [info] Installing extension: humao.rest-client
2022-11-11 11:31:12.296 [error] Error while installing the extension: humao.rest-client
2022-11-11 11:31:12.297 [error] Failed to install extension. humao.rest-client
2022-11-11 11:31:12.298 [error] Extract: ENOENT: no such file or directory, open '/home/build/.vscode-server/extensionsCache/humao.rest-client-0.25.1'
    at x.extractAtLocation (/vscode/vscode-server/bin/linux-alpine/6261075646f055b99068d3688932416f2346dd3b/out/vs/server/node/server.main.js:146:86417)
    at async x.extractUserExtension (/vscode/vscode-server/bin/linux-alpine/6261075646f055b99068d3688932416f2346dd3b/out/vs/server/node/server.main.js:146:83786)
    at async V.extract (/vscode/vscode-server/bin/linux-alpine/6261075646f055b99068d3688932416f2346dd3b/out/vs/server/node/server.main.js:146:90890)
    at async V.doRun (/vscode/vscode-server/bin/linux-alpine/6261075646f055b99068d3688932416f2346dd3b/out/vs/server/node/server.main.js:146:92290)
```

Other VS Code extensions work in the same container. The REST Client works on other remote hosts (I only tested in WSL, but not other Docker containers)

**Comment by bjanders** [comment]
I restarted my computer (and the container), and now installation works. I don't know what caused the error previously.
