### ISSUE TITLE
Connection Reject by Host

### ISSUE THREAD

**Issue by jtsom** [Huachao/vscode-restclient#1279]
- REST Client Version: 0.25.1
- VSCode Version: 1.91.0 (Insiders)
- OS Version: Windows 11

(Adding this report, as the previous one is over a year old with no updates)

Trying to send any request results in Connection Rejected.

![image](https://github.com/Huachao/vscode-restclient/assets/13488/e895dd05-f379-4550-b378-7039ce565713)

Errors messages:

```
[Error - 3:25:46 PM] Failed to send request:
RequestError: The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError.
	at ClientRequest.<anonymous> (c:\Users\jtsombakos\.vscode-insiders\extensions\humao.rest-client-0.25.1\dist\extension.js:252:3306)
	at Object.onceWrapper (node:events:629:26)
	at ClientRequest.emit (node:events:526:35)
	at e.emit (c:\Users\jtsombakos\.vscode-insiders\extensions\humao.rest-client-0.25.1\dist\extension.js:558:29932)
	at TLSSocket.socketErrorListener (node:_http_client:495:9)
	at TLSSocket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```
Steps to Reproduce:

1. Try to send request

Oddly, running the exact same code, but with the release version of VS Code (1.90.2), can send the request successfully without error.

**Comment by Alumniminium** [comment]
Confirming the same issue with 1.93.0
