### ISSUE TITLE
Crash on big json response

### ISSUE THREAD

**Issue by arturock** [Huachao/vscode-restclient#228]
- VSCode Version: 1.25.1
- OS Version: Debian 8.11
- REST Client Version: 0.19.0

Steps to Reproduce:

1. Request
```http
GET https://api.mercadolibre.com/sites/MLA/categories/all HTTP/1.1
Content-Type: application/json
```

An out of memory rises and extension host dies. From the log, seems jsonc-parser is the culprit

```
[Extension Host] debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

/home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:3041 [Extension Host] debugger inspector at %c 1: 
/home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:3041 [Extension Host] debugger inspector at %cnode::Abort() [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 2: 0x7f74c66c76d7 [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 3: 0x7f74c5e8fc07 [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 4: 0x7f74c5e8fb85 [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 6: 0x7f74c5e3d413 [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 7: v8::internal::Factory::NewProperSubString(v8::internal::Handle<v8::internal::String>, int, int) [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 8: 0x7f74c6387b61 [/home/Dev/Applications/VSCode-linux-x64/libnode.so]
 9: 0x1ace8808437d
%c
<--- Last few GCs --->

[9535:0x341845898000]  9389069 ms: Mark-sweep 1995.1 (2056.7) -> 1995.1 (2023.7) MB, 29061.1 / 0.0 ms  last resort 
[9535:0x341845898000]  9394818 ms: Mark-sweep 1995.1 (2023.7) -> 1995.1 (2023.7) MB, 5749.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x12b8197ab959 <JS Object>
    1: substring(this=0x148f9d137171 <Very long string[169752787]>,0,169752776)
    2: applyEdit [/home/Dev/.vscode/extensions/humao.rest-client-0.19.0/node_modules/jsonc-parser/lib/umd/edit.js:175] [pc=0x1ace89011ea7](this=0x33c04879c1c9 <an Object with map 0x151e67a511a1>,text=0x148f9d137171 <Very long string[169752787]>,edit=0x85bb1925db1 <an Object with map 0x36ef09bac471>)
    3: applyEd...


index.js:5 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
onError @ index.js:5
events.js:163 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)
/home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:3136 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
w._onExtensionHostCrashed @ /home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:3136
/home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2364 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /home/Dev/Applications/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js:2364
```

**Comment by Huachao** [comment]
@arturock in my test, does this response body really a JSON file?
[output.json.txt](https://github.com/Huachao/vscode-restclient/files/2212184/output.json.txt)

**Comment by arturock** [comment]
I checked the headers and it corresponds to a gzipped response:

```
curl -I  https://api.mercadolibre.com/sites/MLA/categories/all

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4878643
Connection: keep-alive
Date: Fri, 20 Jul 2018 01:54:32 GMT
Accept-Ranges: bytes
Last-Modified: Fri, 20 Jul 2018 01:07:06 GMT
X-Timestamp: 1532048826.68124
X-Trans-Id: tx98aa044562ed4f7fa6ad2-005b5140d8
X-Content-Type-Options: nosniff
X-Request-Id: 04894151-f7ba-4ae5-8239-76c1121c195c
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Access-Control-Max-Age: 86400
Cache-Control: max-age=300
Content-Encoding: gzip
X-Content-Created: 2018-07-20T01:07:06.270Z
X-Content-MD5: a9b692aa9ee90ef6dcbfe038940049c1
X-Cache: Miss from cloudfront
Via: 1.1 330fd6eb0bbac4274bd35a23c4c6e97c.cloudfront.net (CloudFront)
X-Amz-Cf-Id: bDzFxSnEk4NIfk3o3eVhhrGk_1jaB63kYIwTpyS1rLZviar7TGlLBg==
```

I performed the same request using another lib and got a (big) result, so after seeing the error log I thought the problem was not the response content but the size, however when using curl, the `--compressed` flag is needed for the real contents to be displayed. May be that gzip is not supported?

Btw, I love this extension.

**Comment by Huachao** [comment]
@arturock I can reproduce this issue, and the root cause is that the data is too large (around 170MB), and my suggestion is that if the JSON response body size is larger than a given threshold, no beautify will be done. However, I found VSCode seems can't render the response in webview of VSCode, as well as I can't open such large file in text document of VSCode.

So current plan is to stop formating the response body for file size larget than a given threshold (e.g., 20MB) to avoid heap out of memory. Do you think it's OK for you?

And I will keep this issue open and add the *upstream* tag.

**Comment by arturock** [comment]
Well, response is absurdly long in this case. Yes, a threshold to keep the extension from formatting when the response is too big would work great. It may worth to consider a second limit to avoid the extension to collapse on edge cases.

**Comment by Huachao** [comment]
@arturock Do you still meet the crash problem in latest version 0.20.2?

**Comment by arturock** [comment]
I can happily confirm there are no more crashes with same request using v0.20.2

On the other hand, now I'm getting an alert, and after some waiting an apparently compressed data is displayed

> The content type of response is application/json, while response body is not a valid json string

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4663779
Connection: keep-alive
Date: Mon, 22 Oct 2018 16:44:35 GMT
Accept-Ranges: bytes
Last-Modified: Mon, 22 Oct 2018 16:08:00 GMT
X-Timestamp: 1540224480.76823
X-Trans-Id: tx6d0e112f69164667956c2-005bcdfe73
X-Content-Type-Options: nosniff
X-Request-Id: 6d010379-1cdd-4dd3-ba83-e5d39dbd0353
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Access-Control-Max-Age: 86400
Cache-Control: max-age=300
Content-Encoding: gzip
X-Content-Created: 2018-10-22T16:08:00.463Z
X-Content-MD5: 1ee47a2d98f1b91c81b3d20a9de88e06
X-Cache: Miss from cloudfront
Via: 1.1 6d16d2818c50321b66b1b610e66ba25d.cloudfront.net (CloudFront)
X-Amz-Cf-Id: zoqpnMrX-p2IRkfT5Iu0vDfAXbuQm4wCYqEQg8uXDIyHAcp0OVgBPw==

����KS�H�7��
6�M�;O�TzW.�M7�О�y�w))d�$Zz��������ļ�;���{C*0�T*�0*����Gf*u�����w�Ō���;Q�����;�XȝW;�Xd�O.E&&�i��;?�\FAQf��(��W?���<-�@�?.�E����Q��4��)Z�s��D!��8�����p��1�AJ�LΫ?!������Ϋ���v���YT�E~%g�E����＂��v.Eqq6���Y���Ϋ�u�-�!W�U�<͢�vc���_A����p�K�A����s�\Of�(�(���/�>����v��(3���#��Ϋ��_?숢�"�,�Yq}Y=�R.�"J��굉���� M
�;��"��;~y%�g"��?d�������4��P��YT�%�;?�2(�4٩�%
��ga�Q�ܑs�����������`z|x���N�^�L��3�IQ-3I��􇝠�2��m�L�O*�y&ΣX~]j�X�0�<�׋z;������z���¨Z]
T����V~)�h-�T���ɫH��ߟ��_����9����Y(� �.�?s�伸�y���?�����Rf�5�y����Jd՝\���ϊ���WXv�_�O��i�(g�YȻ������Y�f�'��w����q!�B��7y,�d���)�Md2�ٕ������x&�ꃸ{U���N��I(�3����/"�q\--M
...
```

**Comment by arturock** [comment]
Got it. Thanks!
