### ISSUE TITLE
Copy request as cURL not working

### ISSUE THREAD

**Issue by elonmallin** [Huachao/vscode-restclient#308]
- VSCode Version: 1.30.1
- OS Version: Windows 10 (Windows_NT x64 10.0.17134)
- REST Client Version: 0.21.0

Steps to Reproduce:

1. Highlight `GET www.google.com`.
2. Open command palette and choose "Copy request as cURL".
3. Paste and see that it didn't work.

I got an error and opened the dev tools to see:
```
notificationsAlerts.ts:38 Error: The system cannot find the path specified.

    at Function.module.exports.e.exports.sync (C:\Users\elon\.vscode\extensions\humao.rest-client-0.21.0\dist\extension.js:7:18063)
    at Object.copySync (C:\Users\elon\.vscode\extensions\humao.rest-client-0.21.0\dist\extension.js:274:38432)
    at Object.module.exports.t.writeSync.e [as writeSync] (C:\Users\elon\.vscode\extensions\humao.rest-client-0.21.0\dist\extension.js:12:73384)
    at w.<anonymous> (C:\Users\elon\.vscode\extensions\humao.rest-client-0.21.0\dist\extension.js:162:326074)
    at Generator.next (<anonymous>)
    at o (C:\Users\elon\.vscode\extensions\humao.rest-client-0.21.0\dist\extension.js:162:323181)
    at <anonymous>
t.onDidNotificationChange @ notificationsAlerts.ts:38
```
Got another error the second time I tried:
```
An unknown error occured. Please consult the log for more details.

t.onDidNotificationChange | @ | notificationsAlerts.ts:38
-- | -- | --
(anonymous) | @ | notificationsAlerts.ts:26
e.fire | @ | event.ts:228
t.notify | @ | notifications.ts:113
t.error | @ | notificationService.ts:48
t.onError | @ | commandsHandler.ts:325
(anonymous) | @ | commandsHandler.ts:310
_tickCallback | @ | internal/process/next_tick.js:188
Promise rejected (async) |   |  
(anonymous) | @ | commandsHandler.ts:306
setTimeout (async) |   |  
t.runAction | @ | commandsHandler.ts:296
t.run | @ | commandsHandler.ts:280
e.run | @ | quickOpenModel.ts:585
t.elementSelected | @ | quickOpenWidget.ts:556
(anonymous) | @ | quickOpenWidget.ts:235
```

**Comment by pranayrauthu** [comment]
@Huachao Thanks it's working fine with version 0.21.1

**Comment by elonmallin** [comment]
Thanks, it's working!
