### ISSUE TITLE
Can't send a boolean parameter in the body of a requisition

### ISSUE THREAD

**Issue by gajomon** [Huachao/vscode-restclient#510]
- VSCode Version: 1.41.1
- OS Version: Windows 7
- REST Client Version: 0.23.1

Steps to Reproduce:

1. I have an attribute in a model of my database that has a boolean value, and I have routes to update this field in my database, but when I try to send this change through the body of the requisition it gives me an error in JSON. I have used Insomnia to test this API too, and there it works fine, doing what it is supposed to do.
2. The PUT request I'm sending is:

PUT http://localhost:3333/projetos/5e3ac07099a7df146c014161
Content-Type: application/json

{   
    "arquivado": true,
}

* It receives the ID of the file that will be changed. I'm having this problem:

SyntaxError: Unexpected token } in JSON at position 30
    at JSON.parse (<anonymous>)
    at parse (C:\Users\projetista11\Desktop\Programas\FULL_PLANS-branchFull\backend\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\projetista11\Desktop\Programas\FULL_PLANS-branchFull\backend\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\projetista11\Desktop\Programas\FULL_PLANS-branchFull\backend\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\projetista11\Desktop\Programas\FULL_PLANS-branchFull\backend\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\projetista11\Desktop\Programas\FULL_PLANS-branchFull\backend\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by Huachao** [comment]
@gajomon your request body is not a valid JSON, you should remove the trailing comma after `true`

**Comment by gajomon** [comment]
Ok, I'll try this

**Comment by gajomon** [comment]
It worked, thanks!! I was using Insomnia to make this request, but honestly I prefer your REST Client because it is right in VS Code. :+1: :100:
