### ISSUE TITLE
Connection is being rejected for localhost

### ISSUE THREAD

**Issue by heneds** [Huachao/vscode-restclient#523]
Expectation: If I specify "localhost" in the host address the request should not change to "127.0.0.1".

Some web servers (in this case II Express) do not recognize 127.0.0.1. The server gets the request but is not be able to map against the correct web application.

Symptom:
>Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:63353.

See also #122

Steps to Reproduce:

1. Run a web app from Visual Studio using IIS Express and http
2. Any REST Client request to localhost will get the response ECONNREFUSED 127.0.0.1

- VSCode Version: 1.42.0
- OS Version: Windows 10 
- REST Client Version: 0.23.1
- Visual Studio Version: 16.4.3 with a .NET Core 2.2 web app

![2020-02-12 13_47_05-Home page - WebApplication1](https://user-images.githubusercontent.com/2995852/74336456-9482e800-4d9e-11ea-80a3-aaf84e8338ee.png)

**Comment by Bilosista** [comment]
I have a similar behavior using REST Client with PHP (Slim Framework). It "worked" before (version _0.22.2_), but doesn't anymore (versions _0.23.0_ and _0.23.1_).

After I start the server using `php -S localhost:8080 -t src/`, I also get:

> Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:8080.

But this "worked" like this before. The difference is that now, once I start the server using `php -S 127.0.01:8080 -t src/`, I always get a 401 when trying to send a request from REST Client even though it works from my Ionic/Angular application and also after entering the URL directly in the browser.

- Version: 1.42.1
- Commit: c47d83b293181d9be64f27ff093689e8e7aed054
- Date: 2020-02-11T14:44:27.652Z
- Electron: 6.1.6
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Darwin x64 19.3.0

**Comment by Huachao** [comment]
@Bilosista What's your auth

**Comment by Bilosista** [comment]
@Huachao It’s Basic auth. No idea why, I can try to check tomorrow (I’m using `tuupola/slim-basic-auth`), but it works fine when started using 127.0.0.1 with _0.22.2_, but doesn’t with _0.23.0_ nor _0.23.1_. Did something change in _0.23.0_?

**Comment by Huachao** [comment]
@Bilosista I switched my underlying http client package from `request` to `got`, as well as some other changes. Can you show me your actual request, especially the line of `Authorization`

**Comment by Bilosista** [comment]
@Huachao Sure, here you go...

The request (I also tried with `Authorization: Basic QWRtaW46aGVzbG8=`):

> GET http://localhost:8080/api/heslo/heslo
> Authorization: Basic Admin heslo

The 401 response (using version _0.23.1_):

> HTTP/1.1 401 Unauthorized
> Host: localhost:8080
> Date: Mon, 17 Feb 2020 08:25:03 GMT
> Connection: close
> X-Powered-By: PHP/7.3.11
> Authorization: Basic QWRtaW46aGVzbG8=
> WWW-Authenticate: Basic realm="Protected"
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Headers: X-Powered-By, X-Requested-With, Content-Type, Accept, Origin, Authorization
> Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
> Content-type: text/html; charset=UTF-8

The correct response (using _0.22.2_):

> HTTP/1.1 200 OK
> Host: localhost:8080
> Date: Mon, 17 Feb 2020 08:30:20 GMT
> Connection: close
> X-Powered-By: PHP/7.3.11
> Authorization: Basic QWRtaW46aGVzbG8=
> Content-Type: application/json; charset=utf-8
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Headers: X-Powered-By, X-Requested-With, Content-Type, Accept, Origin, Authorization
> Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
> 
> {
>   "heslo": "heslo",
>   "hash": "$2y$10$egJwZRiT958V0isuxEczG.ToT9Un5kk8d3rk4r3AZpxsElKLVsXc6"
> }

**Comment by Huachao** [comment]
@Bilosista It seems that I didn't handle the auth challenge case, I will update my code

**Comment by Huachao** [comment]
@Bilosista can you try this version, and you need to manually remove the `.txt` in the file name, and install it in the Extensions tab of VSCode by clicking `...`, and select `Install From VSIX` 
[rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4215053/rest-client-0.23.1.vsix.txt)

**Comment by Bilosista** [comment]
@Huachao Yeah, it works ;)

**Comment by vaclavbenes** [comment]
I have same problem on macOs Catalina `10.15.3` with version 0.23.2

![Screenshot 2020-04-27 at 17 32 40](https://user-images.githubusercontent.com/25709267/80390726-1ddd8d00-88ad-11ea-9a03-606acdeb84cc.png)


and curl works 
```bash
╰─$ curl -H "Content-Type: application/json" --request POST -d '{"name":"Joe Doe"}' --url "http://localhost:8000" ; echo $?
0
```

**Comment by Huachao** [comment]
@vaclavbenes can you work with tools like Postman?

**Comment by vaclavbenes** [comment]
@Huachao. Yes I can. Problem is not in curl or Postman. They work fine. 
I thought its related to firewall, but i can send POST from `curl` or `postman` . I ve tried different versions of client. its same behaviour.

**Comment by Huachao** [comment]
@vaclavbenes how can I setup a test environment like you?

**Comment by vaclavbenes** [comment]
**vscode version**
Version: 1.45.0-insider
Commit: abb4a35cfc26102f93fd00df7b59ce1a19c2017a
Date: 2020-04-28T05:34:21.109Z (5 hrs ago)
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

my server

```typescript
import { Drash } from "https://deno.land/x/drash@v0.41.1/mod.ts";

const docker = {
  image: "localtestimagecentos:latest",
  server: "http://192.168.1.104:8080",
  user: "device",
  verifications: 0,
};

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"];
  public GET() {
    this.response.body = JSON.stringify(docker);
    return this.response;
  }

  public POST() {
    const image = this.request.getBodyParam("name");

    if (!image) {
      throw new Drash.Exceptions.HttpException(
        400,
        "This resource requires the `image` body param.",
      );
    }

    console.log(image);

    return this.response;
  }
}

const server = new Drash.Http.Server({
  response_output: "text/html",
  resources: [HomeResource],
});

const hostname = "localhost";
const port = 8000;

console.log(`http://${hostname}:${port}`);

server.run({
  hostname: hostname,
  port: port,
});
```

install deno https://deno.land/
run with `deno -A example.ts`


curl command
```bash
curl -H "Content-Type: application/json" --request POST -d '{"name":"Joe Doe"}' --url "http://localhost:8000"
```

**Comment by Huachao** [comment]
@vaclavbenes I can't repro with your deno example, can you check your settings in VSCode like `http.proxy`?

**Comment by Huachao** [comment]
@vaclavbenes I can't repro with your deno example, can you check your settings in VSCode like `http.proxy`?

**Comment by Huachao** [comment]
@vaclavbenes I can't repro with your deno example, can you check your settings in VSCode like `http.proxy`?

**Comment by vaclavbenes** [comment]
@Huachao  its strange , i removed all settings from user-settings and its no working.

**Comment by vaclavbenes** [comment]
```
RequestError: Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:8000.
    at ClientRequest.<anonymous> (/Users/vaclav.benes/.vscode-insiders/extensions/humao.rest-client-0.23.2/dist/extension.js:252:3573)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:208:15)
    at ClientRequest.e.emit (/Users/vaclav.benes/.vscode-insiders/extensions/humao.rest-client-0.23.2/dist/extension.js:566:29752)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by vaclavbenes** [comment]
I did progress. Plugin works with node-js express example, but not working with deno server example. I move to https://github.com/drashland/deno-drash

**Comment by Hatgor** [comment]
Has similar issue with my node-js express app. 
My OS is Windows 10, 
REST Client version is 0.23.2

Server is hosted on `localhost:3000`

Test request is 
`@url = "http://localhost:3000/"`
`GET {{url}}`

Error message: 
> Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:443.

Postman face no such issues.

**Comment by Huachao** [comment]
@Hatgor as for your case, the added additional double quotes around the URL, removing it should work.

**Comment by Hatgor** [comment]
> @Hatgor as for your case, the added additional double quotes around the URL, removing it should work.

Thanks! It's working now =)

**Comment by lucasluca** [comment]
Im facing the same issue in MacOs Catalina

**Comment by mensand** [comment]
I have the same problem also.  

The URL is defined as 

https://localhost:44391/.well-known/openid-configuration
And the error is on
https://127.0.0.1:44391/.well-known/openid-configuration

Do you know why the localhost is replaced with 127.0.0.1 IP address. The IISExpress is only listening on localhost by name

**Comment by interglobalmedia** [comment]
Hi, I also have the same problem when trying use POST request on localhost. a GET request on a production url is fine. Just POST request on localhost is causing a problem for me.

I created a .txt file I called rest-client.txt. When I read this thread, I tried to install via vsix, and the file was not recognized. Neither were any other ones on my computer. What could I be doing wrong? Thanks in advance for any help you might be able to provide me! I'm on version 0.24.2.

**Comment by interglobalmedia** [comment]
I tried again, and now everything for some reason is working. My file is still called rest-client.txt by the way. Now the trick will be to reproduce this!

**Comment by interglobalmedia** [comment]
Hi, again, so far I have been able to and am starting to get how this works. It's actually much better using this extension that works directly with the code you are building instead of mock third party service code. Thanks!

**Comment by interglobalmedia** [comment]
Hi again,

Now everything works exactly as expected when I use req.body in my index.js (server file) for my Node.js/Express/MongoDB application. One thing that was causing issues but I didn't check at first was that I would get disconnected from the server and that is why things ended up not working. Now I just have to double check before I hit "Send Request". That must be something either with nodemon or VS Code itself. Thanks!

**Comment by mohadel92** [comment]
> @Hatgor as for your case, the added additional double quotes around the URL, removing it should work.

thanks

**Comment by buyaoshushu** [comment]
> @Bilosista can you try this version, and you need to manually remove the `.txt` in the file name, and install it in the Extensions tab of VSCode by clicking `...`, and select `Install From VSIX`
> [rest-client-0.23.1.vsix.txt](https://github.com/Huachao/vscode-restclient/files/4215053/rest-client-0.23.1.vsix.txt)

can't sent any curl request  on version 0.24.2.  downgrade to 0.23.1 anything goes well.

**Comment by leviethung2103** [comment]
I am confirming the double quotes would cause the problem. Just simply remove it and everything goes well.

**Comment by nikitajaiswal0902** [comment]
@Huachao I am facing this issue.
![error](https://user-images.githubusercontent.com/51615724/100431787-a419b600-30be-11eb-99fd-fa8c4d5e7443.png)

My request is :- 
POST http://localhost:8091/api/provider/token HTTP/1.1
Content-Type: application/json
Authorization: Basic XXXXXXXXXXXXXX

I am sending this request via VS code.

**Comment by hyperloo** [comment]
> 
> 
> @Hatgor as for your case, the added additional double quotes around the URL, removing it should work.

This works for me. 

Either declare variable like this **without quotes**
![image](https://user-images.githubusercontent.com/43092030/111586846-72e90100-87e7-11eb-80fa-9135e7e4c381.png)

or write request url like 
![image](https://user-images.githubusercontent.com/43092030/111586952-90b66600-87e7-11eb-83d1-4531e9ebe458.png)

**Comment by snyang** [comment]
Found same issue via tomcat 9.0.45. My tomcat cannot be accessed via `http://127.0.0.1:8080`，but `localhost:8080` is good. 
is rest-client converting `localhost` to `127.0.0.1`?

my request is:

```txt
###
# @name echo
GET http://localhost:8080/sms/api/echo
Content-Type: application/json;
```

The error is
```txt
The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:8080.
```

**Comment by equalamount** [comment]
> Found same issue via tomcat 9.0.45. My tomcat cannot be accessed via `http://127.0.0.1:8080`，but `localhost:8080` is good.
> is rest-client converting `localhost` to `127.0.0.1`?
> 
> my request is:
> 
> ```
> ###
> # @name echo
> GET http://localhost:8080/sms/api/echo
> Content-Type: application/json;
> ```
> 
> The error is
> 
> ```
> The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:8080.
> ```

Yeah, it looks like it's converting it to 127.0.0.1. I just changed my settings, so now my PHP server now runs on 127.0.0.1 IP and everything works fine.

**Comment by rpsingh009** [comment]
> > Found same issue via tomcat 9.0.45. My tomcat cannot be accessed via `http://127.0.0.1:8080`，but `localhost:8080` is good.
> > is rest-client converting `localhost` to `127.0.0.1`?
> > my request is:
> > ```
> > ###
> > # @name echo
> > GET http://localhost:8080/sms/api/echo
> > Content-Type: application/json;
> > ```
> > 
> > 
> > The error is
> > ```
> > The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:8080.
> > ```
> 
> Yeah, it looks like it's converting it to 127.0.0.1. I just changed my settings, so now my PHP server now runs on 127.0.0.1 IP and everything works fine.

how did you change it ?

**Comment by daniel-filipe-lobo** [comment]
For those who waste a whole day trying to find the solution that you think that is a problem with node, or IIS Express, etc. The problem for me was related with this:
https://stackoverflow.com/questions/34543443/cant-access-127-0-0-1

**Comment by kmylo** [comment]
> Expectation: If I specify "localhost" in the host address the request should not change to "127.0.0.1".
> 
> Some web servers (in this case II Express) do not recognize 127.0.0.1. The server gets the request but is not be able to map against the correct web application.
> 
> Symptom:
> 
> > Connection is being rejected. The service isn’t running on the server, or incorrect proxy settings in vscode, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:63353.
> 
> See also #122
> 
> Steps to Reproduce:
> 
> 1. Run a web app from Visual Studio using IIS Express and http
> 2. Any REST Client request to localhost will get the response ECONNREFUSED 127.0.0.1
> 
> * VSCode Version: 1.42.0
> * OS Version: Windows 10
> * REST Client Version: 0.23.1
> * Visual Studio Version: 16.4.3 with a .NET Core 2.2 web app
> 
> ![2020-02-12 13_47_05-Home page - WebApplication1](https://user-images.githubusercontent.com/2995852/74336456-9482e800-4d9e-11ea-80a3-aaf84e8338ee.png)

are you running under WSL? I had similar problem and everything worked with CMD
https://stackoverflow.com/questions/64763147/access-a-localhost-running-in-windows-from-inside-wsl2

**Comment by RajaTheKing826** [comment]
its not sending the Authorization header for local host url, when I tried to send Authorization header for a lamda gate-way url its working fine, But when i try to send Authoriation header for localhost url its nor working 
getting 401 Authorization header not included

**Comment by adamthegeek** [comment]
the solution was very simple for me.
after building the server file, i forgot to run nodejs or nodemone to start/refresh the server.
you simply need to initate it before posting requests

**Comment by kimcatsb** [comment]
Spent all day trying to solve this issue but can't seem to get around it issue.
Background:
I ran my app in WSL2 environment.
On my host machine, I can reach it with "localhost:3000", but "127.0.0.1:3000" will not reach it.
It has something to do with WSL2 mapping "localhost" to VM processes but not 127.0.0.1.  

Is there a way we can prevent REST Client from converting "localhost" into "127.0.0.1"?

**Comment by kimcatsb** [comment]
Answering my own question.
I found a solution for my use case.
Basically, I run another instance of VisualStudio Code within WSL2 environment.

1. Open WSL2 (I'm using ubuntu 20.04), 
2. Type `code .` this will install a copy of Visual Studio Code, open VSC in the directory.
3. Visual Studio Code window will pop up on the desktop. 
4. Install this REST Client
5. Create a .rest file
6. With "localhost"or "127.0.0.1"will reach my service.

**Comment by aderchox** [comment]
I fixed it. @kimcatsb is completely right. The issue will be fixed for WSL2 users if this extension stops turning `localhost` into `127.0.0.1`. When localhost turns into 127.0.0.1, it will point to **the actual Windows OS, i.e., the WSL2's host**, and not the WSL2 vm itself.

There are multiple solutions to this. The quickest one is, run `ip a | grep inet` in WSL2 and use its actual IP address. So your requests will become something this:
```
GET http://172.18.228.135:3000/api/foo
```
However, this solution isn't great as WSL2's IP address is not static (it will change).
So I also ask @Huachao to fix this issue for WSL2 users too. Thanks.

**Comment by mitaloammon** [comment]
only run the application in your terminal 🤷‍♂️

**Comment by karliell** [comment]
> 

I met the same error. However, it doesn't work for my case. I have 
- REST Client Version: v0.25.1
- VSCode Version: Apple silicon [Version 1.73](https://code.visualstudio.com/updates)
- OS Version: Monterey 12.6

**Comment by jvannistelrooy** [comment]
> I somehow fixed it. @kimcatsb is completely right. The issue will be fixed for WSL2 users if this extension stops turning `localhost` into `127.0.0.1`. When localhost turns into 127.0.0.1, it will point to **the actual Windows OS, i.e., the WSL2's host**, and not the WSL2 vm itself.
> 
> There are multiple solutions to this. The quickest one is, run `ip a | grep inet` in WSL2 and use its actual IP address. So your requests will become something this:
> 
> ```
> GET http://172.18.228.135:3000/api/foo
> ```
> 
> However, this solution isn't great as WSL2's IP address is not static (it will change). Another solution would be using Windows cmd which is a nightmare for many unixy people. So I also ask @Huachao to fix this issue for WSL2 users. Thanks.

I'm running into the the above issue too. Converting `localhost` to `127.0.0.1` breaks this extension for me on MacOS Ventura. It would be great if `localhost` would not be converted anymore.

**Comment by deepakChourasiya-aj** [comment]
The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:9090.


/so what is the solution me also showing same error

**Comment by mrmign** [comment]
The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:40601.

**Comment by fhdiaze** [comment]
> I somehow fixed it. @kimcatsb is completely right. The issue will be fixed for WSL2 users if this extension stops turning `localhost` into `127.0.0.1`. When localhost turns into 127.0.0.1, it will point to **the actual Windows OS, i.e., the WSL2's host**, and not the WSL2 vm itself.
> 
> There are multiple solutions to this. The quickest one is, run `ip a | grep inet` in WSL2 and use its actual IP address. So your requests will become something this:
> 
> ```
> GET http://172.18.228.135:3000/api/foo
> ```
> 
> However, this solution isn't great as WSL2's IP address is not static (it will change). Another solution would be using Windows cmd which is a nightmare for many unixy people. So I also ask @Huachao to fix this issue for WSL2 users. Thanks.

Thanks

> IP

Hi, thanks it worked for me.

**Comment by FlaviodosSantos** [comment]
> De alguma forma eu consertei.@kimcatsbestá completamente certo. O problema será corrigido para usuários do WSL2 se esta extensão parar de se transformar `localhost`em `127.0.0.1`. Quando o localhost se transformar em 127.0.0.1, ele apontará para **o sistema operacional Windows real, ou seja, o host do WSL2** e não o próprio WSL2 vm.
> 
> Existem várias soluções para isso. O mais rápido é executar `ip a | grep inet`no WSL2 e usar seu endereço IP real. Assim, seus pedidos se tornarão algo assim:
> 
> ```
> GET http://172.18.228.135:3000/api/foo
> ```
> 
> No entanto, esta solução não é boa, pois o endereço IP do WSL2 não é estático (ele mudará). Outra solução seria usar o cmd do Windows, que é um pesadelo para muitas pessoas unixy. Então eu também pergunto@Huachaopara corrigir esse problema para usuários do WSL2. Obrigado.

Thank you very much

**Comment by Hamada-Ali** [comment]
for those who still have this issue :

solution 1 :

- just enable this features in control panel > program and features > turn windows features on or off > enable internet information hostable web core and also enable World wide web services in internet information services


solution 2 :

- you can just change the localhost (127.0.0.1) to 0.0.0.0 in your API Client and the problem will be solved .

**Comment by Pestilence01** [comment]
> I was having the same issue with REST Client. So I checked the address my webserver was listening on using
> 
> ```
> netstat -aon
> ```
> 
> There I found that my server was binding to `[::1]`. So after replacing `localhost` with `[::1]`
> 
> ```
> GET http://[::1]:12345
> ```
> 
> REST Client is now able to contact my server.

You are a life saver. This issue has been bugging me for days now. Your solution is the ONLY one that was able to fix the issue. Thank you from the bottom of my heart.

**Comment by Josimar-Bezerra** [comment]
> I was having the same issue with REST Client. So I checked the address my webserver was listening on using
> 
> ```
> netstat -aon
> ```
> 
> There I found that my server was binding to `[::1]`. So after replacing `localhost` with `[::1]`
> 
> ```
> GET http://[::1]:12345
> ```
> 
> REST Client is now able to contact my server.



> I was having the same issue with REST Client. So I checked the address my webserver was listening on using
> 
> ```
> netstat -aon
> ```
> 
> There I found that my server was binding to `[::1]`. So after replacing `localhost` with `[::1]`
> 
> ```
> GET http://[::1]:12345
> ```
> 
> REST Client is now able to contact my server.

Thank you so much for sharing your solution. I've been trying to find one that works for my situation and this one has gotten the job done.

**Comment by Josimar-Bezerra** [comment]
> I was having the same issue with REST Client. So I checked the address my webserver was listening on using
> 
> ```
> netstat -aon
> ```
> 
> There I found that my server was binding to `[::1]`. So after replacing `localhost` with `[::1]`
> 
> ```
> GET http://[::1]:12345
> ```
> 
> REST Client is now able to contact my server.

Thank you so much for sharing your solution. I've been trying to find one that works for my situation and this one has gotten the job done.

**Comment by NathanHsuAU** [comment]
I was having the same issue with REST Client. So I checked the address my webserver was listening on using

netstat -aon
There I found that my server was binding to [::1]. So after replacing localhost with [::1]

GET http://[::1]:12345
REST Client is now able to contact my server.


this solution works for me, thanks "A-make" shared this.

**Comment by Aashim-limbu** [comment]
Previously i ran into this trouble while runing the json server 
i had my server running but i was gettion error 
TCP    [::1]:3001             [::]:0                 LISTENING
the solution is that I simply change my host to --host 0.0.0.0 
made sure: 
 TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING
 then boom it start working

**Comment by qtopsoft** [comment]
I am having bit weired issue, tomcat is rejecting fetch calls to node from client machine however, postman returns data to same calls from same client. everything works fine on server machine. cant figure out what is the issue with tomcat

**Comment by slawko** [comment]
I'm getting the same error in VSC when trying to access json-server launched on my computer, but adding "--host 0.0.0.0" or "--host 127.0.0.1" to the json-server command fixed they issue. Yay! Thanks @Aashim-limbu!

**Comment by Aashim-limbu** [comment]
@slawko I'm glad I could be of help.Hope you enjoy your jorney
