### ISSUE TITLE
Parse Error: Header overflow

### ISSUE THREAD

**Issue by darkrice** [Huachao/vscode-restclient#601]
- REST Client Version:0.23.2
- VSCode Version:1.4.6-insider
- OS Version:
win 10 
Steps to Reproduce:

1. send post request  to  server to obtain token
2. restclient give "Parse Error: Header overflow", maybe header length of response message  is longer than 8k.
3. error message as bellow:
[Error  - 上午10:11:55] Failed to send request:
RequestError: Parse Error: Header overflow
	at ClientRequest.<anonymous> (c:\Users\m00287810\.vscode-insiders\extensions\humao.rest-client-0.23.2\dist\extension.js:252:3573)
	at Object.onceWrapper (events.js:291:20)
	at ClientRequest.emit (events.js:208:15)
	at ClientRequest.e.emit (c:\Users\m00287810\.vscode-insiders\extensions\humao.rest-client-0.23.2\dist\extension.js:566:29752)
	at TLSSocket.socketOnData (_http_client.js:456:9)
	at TLSSocket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at TLSSocket.Readable.push (_stream_readable.js:210:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by Huachao** [comment]
@darkrice you are right, and this is the limitation from Node.js which hard code the header max size. I'd like to close it since actually it's not related to my extension itself.

**Comment by bramoo** [comment]
See #820 for a workaround
