### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by rbtrun** [Huachao/vscode-restclient#643]
Hi team, 

I failed to run any script, always popup "socket hang up"

VScode info:
---------------------
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

REST output:
--------------------
[Error - 3:23:24 PM] Failed to send request:
RequestError: socket hang up
	at ClientRequest.<anonymous> (/Users/jonathanlee/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:252:3306)
	at Object.onceWrapper (events.js:291:20)
	at ClientRequest.emit (events.js:208:15)
	at ClientRequest.e.emit (/Users/jonathanlee/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:558:29904)
	at Socket.socketOnEnd (_http_client.js:433:9)
	at Socket.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Error - 3:28:24 PM] Failed to send request:
RequestError: socket hang up
	at ClientRequest.<anonymous> (/Users/jonathanlee/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:252:3306)
	at Object.onceWrapper (events.js:291:20)
	at ClientRequest.emit (events.js:208:15)
	at ClientRequest.e.emit (/Users/jonathanlee/.vscode/extensions/humao.rest-client-0.24.1/dist/extension.js:558:29904)
	at Socket.socketOnEnd (_http_client.js:433:9)
	at Socket.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)

Regards,

**Comment by Huachao** [comment]
@rbtrun did you work previously or set the proxy?

**Comment by opessoa** [comment]
I have this error when use host:port

**Comment by sparkle32817** [comment]
Thanks for your extension, Huachao.
I have same issue.
I have set proxy on vscode.
This is working on local with "rest-client.excludeHostsForProxy" setting.
But can't access to others.
Hope to hear solution asap.
Regards.
