### ISSUE TITLE
在.http文件没有智能提示了

### ISSUE THREAD

**Issue by dongrizhixue** [Huachao/vscode-restclient#65]
- VSCode Version:1.8.1
- OS Version:windows 10
- REST Client Version:0.12.1 

Steps to Reproduce:

1. post、get、content-type等关键字不能自动出现了
2.

**Comment by Huachao** [comment]
@dongrizhixue I can still get auto competition items, could you help to double check it?

**Comment by dongrizhixue** [comment]
其他的都正常，只有提示不行了。
以前打出POST之后会自动生成 POST http://host/api/userinfo HTTP/1.1。但是现在只能全部手动打出来。

**Comment by Huachao** [comment]
@dongrizhixue can headers still work? And if you type POST, the auto generated should be a snippet without that url. And when you type `http://`, the url will be hinted, and the url is from request history. So can you check if the url you mentioned is still in the history?

**Comment by dongrizhixue** [comment]
Not automatically "post".

```http
post http://hq.sinajs.cn/list=sh601006
```

```text
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 251
Connection: Keep-Alive
Content-Type: application/x-javascript; charset=GBK

var hq_str_sh601006="大秦铁路,6.990,6.990,6.980,7.000,6.940,6.970,6.980,22767950,158810164.000,253220,6.970,1569398,6.960,539745,6.950,424600,6.940,317500,6.930,270600,6.980,798000,6.990,810238,7.000,411700,7.010,260500,7.020,2017-02-07,15:00:00,00";
```

**Comment by Huachao** [comment]
@dongrizhixue you still don't have autocompleted post snippet right? What's your language of the file, it must be `HTTP` or `Plain Text`

**Comment by dongrizhixue** [comment]
是的，我的是  .HTTP

**Comment by Huachao** [comment]
@dongrizhixue thanks, and could you check the console of developer tools as I mentioned above, and can you also get other auto completiton items like header name

**Comment by dongrizhixue** [comment]
@Huachao 是的，右下角的状态栏上显示HTTP。

**Comment by Huachao** [comment]
@dongrizhixue Can you find any errors in vscode from the tab `Help` > `Developer Tools`, you can find a Chrome like dev tools, and you can click the Console tab, could you see any errors or warnings?

**Comment by dongrizhixue** [comment]
哦，好的。

```txt
workbench.main.js:138Unexpected number in JSON at position 10366: SyntaxError: Unexpected number in JSON at position 10366
    at fs.readFile (C:\Users\guoxuri\.vscode\extensions\humao.rest-client-0.12.1\out\src\persistUtility.js:118:42)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

```txt
workbench.main.js:133 [Extension Host] Uncaught Exception:  SyntaxError: Unexpected number in JSON at position 10366d.logExtensionHostMessage @ workbench.main.js:133(anonymous function) @ workbench.main.js:133emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
workbench.main.js:133 [Extension Host] SyntaxError: Unexpected number in JSON at position 10366
    at fs.readFile (C:\Users\guoxuri\.vscode\extensions\humao.rest-client-0.12.1\out\src\persistUtility.js:118:42)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)d.logExtensionHostMessage @ workbench.main.js:133(anonymous function) @ workbench.main.js:133emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

```txt
workbench.main.js:133 [Extension Host] SyntaxError: Unexpected number in JSON at position 10366
    at fs.readFile (C:\Users\guoxuri\.vscode\extensions\humao.rest-client-0.12.1\out\src\persistUtility.js:118:42)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)d.logExtensionHostMessage @ workbench.main.js:133(anonymous function) @ workbench.main.js:133emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by dongrizhixue** [comment]
![输入图片说明](http://git.oschina.net/uploads/images/2017/0207/154700_7fd87857_88875.png "在这里输入图片标题")

**Comment by Huachao** [comment]
@dongrizhixue I think it's a bug of my code, can you provide the content of the `history.json` under file path `%USERPROFILE%\.rest-client`, I think it's not a valid json. If so, one way to work around is delete or fix the file content

**Comment by dongrizhixue** [comment]
我找不到history.json文件。怎么办？

**Comment by Huachao** [comment]
@dongrizhixue can you find the folder `C:\Users\guoxuri\.rest-client`?

**Comment by dongrizhixue** [comment]
![输入图片说明](http://git.oschina.net/uploads/images/2017/0207/155645_1bda6d69_88875.jpeg "在这里输入图片标题")

**Comment by dongrizhixue** [comment]
```json
[{"method":"GET","url":"http://115.28.243.48:9006/api/values/GET/1","headers":{"content-type":"application/json; charset=utf-8","User-Agent":"vscode-restclient"},"startTime":1483578981161},{"method":"GET","url":"https://example.com/comments/1","headers":{"User-Agent":"vscode-restclient"},"startTime":1483516155029},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482979792155},{"method":"GET","url":"https://gw.yundzh.com/quote/min?token=0000002f:1483063274:e8095c3a4205ba9b511d3ff4dbc41732a970af11&obj=SH600000","headers":{"User-Agent":"vscode-restclient"},"startTime":1482976905667},{"method":"GET","url":"https://gw.yundzh.com/quote/min?token=0000002f:1483063274:e8095c3a4205ba9b511d3ff4dbc41732a970af11&obj=sh600000","headers":{"User-Agent":"vscode-restclient"},"startTime":1482976897048},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482976872597},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482975265735},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482733997064},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482717246549},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482712572411},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482547311928},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482546684740},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482546465575},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482546453049},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482546217550},{"method":"GET","url":"https://gw.yundzh.com/token/access?appid=091960b506d811e684090242ac1102a4&secret_key=v1Lb7j2YAq97","headers":{"User-Agent":"vscode-restclient"},"startTime":1482545513560},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482545327987},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482545314566},{"method":"GET","url":"https://keyboardstatistics.wilddogio.com/keydata/guoxuri.json","headers":{"User-Agent":"vscode-restclient"},"startTime":1482368078099},{"method":"GET","url":"https://keyboardstatistics.wilddogio.com/keydata/guoxuri.json","headers":{"User-Agent":"vscode-restclient"},"startTime":1482368046953},{"method":"GET","url":"https://keyboardstatistics.wilddogio.com/keydata/guoxuri.json","headers":{"User-Agent":"vscode-restclient"},"startTime":1482368017109},{"method":"GET","url":"https://ydxy.wilddogio.com/roomzbgd/3520160204.json","headers":{"User-Agent":"vscode-restclient"},"startTime":1482367970631},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482303708937},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482213233609},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482203668895},{"method":"GET","url":"https://www.dongri.net.cn/api/stockmarket/yundzhtoken","headers":{"User-Agent":"vscode-restclient"},"startTime":1482201146409},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137962285},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137951791},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137944934},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137568370},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137555684},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137546658},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=fbjKU995uX2kAHOmiAYJ3kKcSLzczx7Xgk79hpse&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137537544},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137512137},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137495143},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137478093},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderBy=\"$key\"","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137456997},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderBy=jid","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137440304},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0Nzk3NzI4MDAuMCwidWlkIjoiMGU4OTUxN2NlZjM1NGU2NGJjZDIyMDVjNjFiYmI3MGEiLCJjbGFpbXMiOnsidGlkIjoiMCwxMDYifX0.PVTpGtgeh7azYwTPHPH7E8e_vDHc7PN3kRkF0gGbR2o&limitToLast=20&orderby=value","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137401460},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderby=value","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137326716},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderby=value","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137322934},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderby=id","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137306211},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20&orderby=id","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137304201},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu&limitToLast=20","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137290835},{"method":"GET","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137199906},{"method":"POST","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137173419},{"method":"POST","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137170958},{"method":"POST","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137154671},{"method":"POST","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137153482},{"method":"POST","url":"https://jff.wilddogio.com/v2/103/szgd.json?auth=f7M8RNtBKzEC1N3P97lCdSK2ygSUwKwICqPJjPRu","headers":{"User-Agent":"vscode-restclient"},"startTime":1482137152042}]482137152042}]
```

**Comment by Huachao** [comment]
@dongrizhixue it should be a bug of my code in some cases write the malformed json file, and simple remove the string `482137152042}]` at the end of the file should work

**Comment by dongrizhixue** [comment]
成功了，又能正常使用了，我很开心。谢谢。

**Comment by Huachao** [comment]
@dongrizhixue sorry for the inconvenience. Thanks for your feedback
