### ISSUE TITLE
Parse Error: Expected HTTP/

### ISSUE THREAD

**Issue by JohnPiepersSmits** [Huachao/vscode-restclient#662]
- REST Client Version: v0.24.1
- VSCode Version: 1.48.0
- OS Version: Windows 10 1909

Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

Using a get request saved in a send.http file (GET http://url HTTP/1.1) it now shows a Parse Error: expected HTTP/

Using a POST, PUT or DELETE to the same local URL does work normally.

This is since the update of vscode to 1.48
With 1.47.x there was no issue at all.

**Comment by Huachao** [comment]
@JohnPiepersSmits could you please show me your actual request or HTTP file

**Comment by JohnPiepersSmits** [comment]
Sure.

This request works:
POST http://website.local/dev/api.php

But if I try a GET to the same local url:
GET http://website.local/dev/api.php

This shows the popup with the Parse Error: expected HTTP/

As I already mentioned, this error is since VSCode was updated to version 1.48
Before that there was no issue at all.

[send-test.zip](https://github.com/Huachao/vscode-restclient/files/5082272/send-test.zip)

**Comment by Huachao** [comment]
@JohnPiepersSmits could you please show me the error details, you can checkout this in the output channel of `REST`

**Comment by vinitdave27** [comment]
I have the same error. Below is the error from the output terminal for the RESTClient extension.
[Error - 1:09:03 PM] Failed to send request:
RequestError: Parse Error: Expected HTTP/
	at ClientRequest.<anonymous> (c:\Users\davevx\.vscode\extensions\humao.rest-client-0.24.2\dist\extension.js:252:3306)
	at Object.onceWrapper (events.js:291:20)
	at ClientRequest.emit (events.js:208:15)
	at ClientRequest.e.emit (c:\Users\davevx\.vscode\extensions\humao.rest-client-0.24.2\dist\extension.js:558:29926)
	at Socket.socketOnData (_http_client.js:456:9)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by Huachao** [comment]
@vinitdave27 could you please show me your request

**Comment by vinitdave27** [comment]
GET http://localhost:5001/api/v1/user/list

**Comment by vinitdave27** [comment]
Same occurs when I perform a POST http://localhost:5001/api/v1/user/add HTTP/1.1
Content-Type: application/json

{
"firstname":"sample"
}

**Comment by Huachao** [comment]
@vinitdave27 could you succeed with `cURL` or other HTTP client tools, and show me the response there if available

**Comment by vinitdave27** [comment]
Yes, I can run the same requests from postman and they successfully run. I don't have the responses right now handy, but I can post later.

**Comment by vinitdave27** [comment]
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
X-DNS-Prefetch-Control: off
Expect-CT: max-age=0
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
X-XSS-Protection: 0
Content-Type: application/json; charset=utf-8
Content-Length: 381
ETag: W/"17d-mnKxXJgcwzUFQPaGWzA2LKiJnuA"
Set-Cookie: connect.sid=s%3AJa_l_SVtXb1sNsKnOTEHE7Miz5EjmWNl.ZoiJqhHBTZv16UBkA3O%2B%2BB1TXJTZQLDGGtL9Uze3k2I; Path=/; Expires=Wed, 02 Sep 2020 14:38:14 GMT; HttpOnly
Date: Wed, 02 Sep 2020 13:38:14 GMT
Connection: keep-alive
Response Body
{"users":[{"firstname":"Jane","lastname":"Doe","_id":"7PRvlmdjRwIz75oa"},{"firstname":"Mark","lastname":"Doe","_id":"GPzRvXMriwEukvab"},{"firstname":"Jacob","lastname":"Doe","_id":"ORD0TDEeBXEfoI8Y"},{"firstname":"John","lastname":"Doe","_id":"Z2McuegN6RQjkgA6"}]}

**Comment by msarm** [comment]
> Same occurs when I perform a POST http://localhost:5001/api/v1/user/add HTTP/1.1
> Content-Type: application/json
> 
> {
> "firstname":"sample"
> }

Any chance, you were able to resolve this issue?

**Comment by carlosdummy14** [comment]
Hi,

I have the same issue.
I think that is the port the problem.

The same app with port 3000 is ok, but with port 5000 or higher didn't work.

**Comment by benblb** [comment]
Same here. Tried 8080, worked. 15555 failed.

**Comment by dgancho** [comment]
I had ports conflict and the same error. Once I resolved the conflict, the error disappeared

**Comment by FieteO** [comment]
I observed the same issue when connecting to an endpoint that was using `HTTP/0.9`:
```sh
$ curl http://localhost:8447
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by cpyyyyyyyyy** [comment]
> * REST Client Version: v0.24.1
> * VSCode Version: 1.48.0
> * OS Version: Windows 10 1909
> 
> Version: 1.48.0 (system setup) Commit: db40434f562994116e5b21c24015a2e40b2504e6 Date: 2020-08-13T07:50:42.600Z Electron: 7.3.2 Chrome: 78.0.3904.130 Node.js: 12.8.1 V8: 7.8.279.23-electron.0 OS: Windows_NT x64 10.0.18363
> 
> Steps to Reproduce:
> 
> Using a get request saved in a send.http file (GET http://url HTTP/1.1) it now shows a Parse Error: expected HTTP/
> 
> Using a POST, PUT or DELETE to the same local URL does work normally.
> 
> This is since the update of vscode to 1.48 With 1.47.x there was no issue at all.

Excuse me, Did you solve this error? I met the same problem when I use a GET request.
