### ISSUE TITLE
Issues with Completion using latest version of vscode

### ISSUE THREAD

**Issue by Fitz1989** [Huachao/vscode-restclient#944]
After updating vscode to latest version, I am no longer seeing code completion in new .rest or .http request files. Below error appears in window log after I try to type an http header in. I have verified that code completion is set to "auto" and the language is chosen as HTTP. 

[2021-12-19 12:22:39.088] [renderer1] [error] Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
	at Function.entries (<anonymous>)
	at c.mapEnvironmentVariables (c:\Users\******\.vscode\extensions\humao.rest-client-0.24.6\dist\extension.js:1:156184)
	at c.getAvailableVariables (c:\Users\******\.vscode\extensions\humao.rest-client-0.24.6\dist\extension.js:1:156090)
	at async c.getAll (c:\Users\******\.vscode\extensions\humao.rest-client-0.24.6\dist\extension.js:1:155710)
	at async Function.getHttpElements (c:\Users\******\.vscode\extensions\humao.rest-client-0.24.6\dist\extension.js:686:23421)
	at async t.HttpCompletionItemProvider.provideCompletionItems (c:\Users\******\.vscode\extensions\humao.rest-client-0.24.6\dist\extension.js:686:11514)
	at async z.provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:101516)

**Comment by Huachao** [comment]
@Fitz1989 could you please your selected environment name from the status bar and inspect the variables belong to this environment in VSCode settings with name `rest-client.environmentVariables`

**Comment by CarBar** [comment]
I had the same issue @Fitz1989 and realized that the environment in the lower right corner of VS Code was set to an environment that didn't exist. Change that to one of the environments defined in your `.vscode/settings.json` file.
<img width="122" alt="image" src="https://github.com/Huachao/vscode-restclient/assets/899194/d185bfb2-6c2e-4198-a59c-84bbf5fbc18a">
