### ISSUE TITLE
TypeError: "e.on is not a function" for a simple REST request

### ISSUE THREAD

**Issue by MoerkyMark** [Huachao/vscode-restclient#957]
- REST Client Version: 0.24.6
- VSCode Version: 1.63.2
- OS Version: macOS monterey 12.1

Steps to Reproduce:

1. Issue following request returns type error
```
### Why is this not working
curl "http://myURL/rest/items/testCO2" \
	-X POST \
	-d "450" \
	-H "Content-Type: text/plain"
```
2. Other requests like the following work fine
```
curl "http://myURL/rest/items/myPushMessage"
	-X POST \
	-d "Testnachricht" \
	-H "Content-Type: text/plain"
```
2. Error is "e.on is not a function" whilst using the same curl on the command-line works fine.
```
TypeError: e.on is not a function
	at /Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:12:11415
	at new Promise (<anonymous>)
	at Object.a [as convertStreamToBuffer] (/Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:12:11382)
	at T.prepareOptions (/Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:7:75035)
	at T.send (/Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:7:74136)
	at v.runCore (/Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:625:921950)
	at v.run (/Users/markus/.vscode/extensions/humao.rest-client-0.24.6/dist/extension.js:625:921556)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async r._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31072)
	at async r._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31072)
```

**Comment by Huachao** [comment]
@MoerkyMark nice catch, I have fixed the issue and will be published in the next release

**Comment by Huachao** [comment]
@MoerkyMark now you can try this in the latest version 0.25.0
